### PR TITLE
feat: add typescript support.

### PR DESCRIPTION
**Pull request by masayuki0220**
Hi,

I have created this Issue(#99) pull request.

Regards,

### CODE REVIEW

**Comment by rolandoesc** [comment]
Hello! I'm interested on this feature to be added on logRocket as I've been experiencing issues with the typing.

Will this be available anytime soon? @farzadso 

Thank you! :)

**Comment by farzadso** [comment]
Much appreciated @masayuki0220 

@rolandoesc TypeScript support is now available starting from `v1.3.0`. Please update your dependencies accordingly.

**Comment by masayuki0220** [comment]
@farzadso 
Thanks for the merge.

The index.d.ts was not added to the public package.
Could you please add index.d.ts to the files in package.json?

I apologize for the inconvenience.

**Comment by farzadso** [comment]
@masayuki0220 Sorry. I totally forgot. Please upgrade to `v1.5.0`.

**Comment by masayuki0220** [comment]
Thanks for the quick response too!

**Pull request merged**
