### PR TITLE
Update scripts and dependencies

### LINKED ISSUE #327: Can't load module – hardcoded paths
```
Error while requiring module nuxt-logrocket: Error [ERR_MODULE_NOT_FOUND]: 
Cannot find module '/home/farzad/projects/oss/nuxt-logrocket/node_modules/jiti/lib/index.js'
imported from /Users/lukaszflorczak/my-project/node_modules/.pnpm/nuxt-logrocket@2.0.0_rollup@2.79.1/node_modules/nuxt-logrocket/dist/module.mjs
```

There are hardcoded paths In `module.d.ts`:
```js
export * from "/home/farzad/projects/oss/nuxt-logrocket/src/module";
export { default } from "/home/farzad/projects/oss/nuxt-logrocket/src/module";
```

and `module.mjs`:
```js
import jiti from "file:///home/farzad/projects/oss/nuxt-logrocket/node_modules/jiti/lib/index.js";

/** @type {import("/home/farzad/projects/oss/nuxt-logrocket/src/module")} */
const _module = jiti(null, { interopDefault: true, esmResolve: true })("/home/farzad/projects/oss/nuxt-logrocket/src/module.ts");

export default _module;
```

### PR DESCRIPTION
**Pull request by jphilung**
Fixes #327, #328, #331 where the prepare script was generating development files

### CODE REVIEW

**Comment by jphilung** [comment]
@farzadso , the error on the distributed files on npm is caused by the stub flag on the nuxt-module-build command which is on the prepare script.

i've also bumped versions or fixed versions for the dev dependencies and realigned the scripts with the current nuxt module starter pack.

**Comment by kcharlesbusiness** [comment]
Any chance this can get merged in? 👀

**Comment by farzadso** [comment]
@jphilung Thanks for the contribution but the `dev` script doesn't work anymore.

image

Also this project uses `yarn` and not `npm` as the package manager, so please take this into account when adding scripts.

the lockfile needs to be updated too.

**Comment by farzadso** [comment]
These changes were made in another commit.

**Pull request closed without merging**
