### PR TITLE
chore!: Support Nuxt 3 & Bridge

### LINKED ISSUE #155: Support for publicRuntimeConfig
Would be nice to support `$config` for `LOGROCKET_ID`, etc.

* Details: https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-runtime-config/
* See for example the way `@nuxtjs/axios` has implemented it: https://github.com/nuxt-community/axios-module/blob/master/lib/plugin.js#L192-L198

### PR DESCRIPTION
**Pull request by Diizzayy**
Closes #155

This PR adds support for Nuxt 3 and Nuxt Bridge.

Additional changes:
- Pinia integration.
- Improved Typescript support.
- Dropped Jest in favor of Vitest

Breaking Changes:
- `logRocketId` has been renamed to `id`.
- `devModeAllowed` has been renamed to `dev`.
- Environment variables are now handled by the runtime config.

### CODE REVIEW

**Comment by Atinux** [comment]
Any update?

**Comment by Atinux** [comment]
cc @farzadso

**Comment by farzadso** [comment]
Thanks and sorry for the delay in replying. I'll review this during the weekend and get it merged and published. @Atinux @Diizzayy

**Comment by farzadso** [comment]
Thank you for your contribution @Diizzayy

**Pull request merged**
